import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { ArrowLeft, Upload, Sparkles, FileText, ArrowRight, Loader2 } from "lucide-react";
import { useProfile } from "@/context/ProfileContext";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { toast } from "sonner";

import { supabase } from "@/lib/supabase";

type Step = "source" | "upload" | "signer" | "options" | "confirm";

export default function NewDocument() {
  const navigate = useNavigate();
  const { profile } = useProfile();
  const [step, setStep] = useState<Step>("source");
  const [source, setSource] = useState<"upload" | "clara" | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);

  // Form Data
  const [file, setFile] = useState<File | null>(null);
  const [title, setTitle] = useState("");

  const [signerName, setSignerName] = useState("");
  const [signerEmail, setSignerEmail] = useState("");
  const [signerNif, setSignerNif] = useState("");
  const [signerPhone, setSignerPhone] = useState("");
  const [signerAddress, setSignerAddress] = useState("");
  const [signatureType, setSignatureType] = useState("full");

  const [customMessage, setCustomMessage] = useState("");
  const [expiresInDays, setExpiresInDays] = useState("7");

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      const selectedFile = e.target.files[0];
      if (selectedFile.type !== 'application/pdf') {
        toast.error("Solo se permiten archivos PDF");
        return;
      }
      setFile(selectedFile);
      if (!title) {
        setTitle(selectedFile.name.replace('.pdf', ''));
      }
    }
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    if (e.dataTransfer.files && e.dataTransfer.files[0]) {
      const selectedFile = e.dataTransfer.files[0];
      if (selectedFile.type !== 'application/pdf') {
        toast.error("Solo se permiten archivos PDF");
        return;
      }
      setFile(selectedFile);
      if (!title) {
        setTitle(selectedFile.name.replace('.pdf', ''));
      }
    }
  };



  const handleCreateDocument = async () => {
    if (!file || !title || !signerEmail || !signerName) return;

    setIsSubmitting(true);
    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error("No estás autenticado");

      // Upload file to Storage (Private bucket)
      // For Phase 0, we can skip storage or just assume public URL if simple.
      // But standard is uploading to 'documents' bucket.
      // Let's stick to the PRD: documents.file_url is TEXT.
      // Ideally we upload first.

      const fileName = `${user.id}/${Date.now()}_${file.name}`;
      const { data: uploadData, error: uploadError } = await supabase.storage
        .from('documents')
        .upload(fileName, file);

      if (uploadError) throw uploadError;

      const { data: publicUrlData } = supabase.storage.from('documents').getPublicUrl(fileName);
      const fileUrl = publicUrlData.publicUrl;

      // Create Document in DB
      const { data: doc, error: insertError } = await supabase
        .from('documents')
        .insert({
          user_id: user.id,
          title,
          file_url: fileUrl,
          status: 'draft',
          signer_name: signerName,
          signer_email: signerEmail,
          signer_phone: signerPhone, // Note: Schema calls it signer_phone, verify field name!
          custom_message: customMessage,
          signature_type: signatureType,
          expires_at: new Date(Date.now() + parseInt(expiresInDays) * 24 * 60 * 60 * 1000).toISOString(),
          // sign_token: Generated by Default or Trigger? Schema says UNIQUE but not DEFAULT gen_random_uuid()
          // We should generate it here.
          sign_token: crypto.randomUUID()
        })
        .select()
        .single();

      if (insertError) throw insertError;

      if (doc?.id) {
        await handleSendDocument(doc.id, user.id);
      }

    } catch (error: any) {
      console.error(error);
      toast.error(error.message);
      setIsSubmitting(false);
    }
  };

  const handleSendDocument = async (docId: string, userId: string) => {
    try {
      // 1. Check & Consume Credit
      const { data: creditResult, error: creditError } = await supabase.rpc('consume_credit', { p_user_id: userId });

      if (creditError) throw creditError;

      // creditResult matches { success: boolean, remaining: integer }
      // RPC returns a set of rows, so single() or array access needed?
      // Function defined as RETURNS TABLE. So we likely get an array `[{ success: true, remaining: 5 }]`

      // Actually `consume_credit` returns TABLE.
      // Let's assume it returns one row.
      const resultRow = (creditResult as any)?.[0];

      if (!resultRow || !resultRow.success) {
        toast.error("No tienes créditos suficientes.");
        navigate('/credits/purchase');
        return;
      }

      // 2. Update Document Status
      const { error: updateError } = await supabase
        .from('documents')
        .update({
          status: 'sent',
          sent_at: new Date().toISOString()
        })
        .eq('id', docId);

      if (updateError) throw updateError;

      // 3. Log Event (Trigger for Webhooks/n8n)
      await supabase.from('event_logs').insert({
        user_id: userId,
        document_id: docId,
        event_type: 'document.sent', // Matching n8n trigger
        event_data: { credits_remaining: resultRow.remaining }
      });

      toast.success("Documento enviado correctamente");
      navigate('/dashboard');

    } catch (error: any) {
      toast.error("Error al enviar: " + error.message);
      navigate('/dashboard');
    }
  };

  const renderStep = () => {
    switch (step) {
      case "source":
        return (
          <div className="space-y-4">
            <h2 className="text-lg font-semibold">¿Cómo quieres crear el documento?</h2>
            <div className="space-y-3">
              <div
                className={`flex items-center gap-4 rounded-xl border p-4 cursor-pointer transition-all hover:bg-slate-50 hover:border-primary/50 hover:shadow-sm ${source === "upload" ? "ring-2 ring-primary border-transparent" : "bg-white"
                  }`}
                onClick={() => setSource("upload")}
              >
                <div className="flex h-12 w-12 items-center justify-center rounded-full bg-blue-50">
                  <Upload className="h-6 w-6 text-primary" />
                </div>
                <div>
                  <p className="font-semibold text-foreground">Subir PDF</p>
                  <p className="text-sm text-muted-foreground">
                    Sube un documento que ya tengas preparado
                  </p>
                </div>
              </div>

              <div
                className={`flex items-center gap-4 rounded-xl border p-4 cursor-pointer transition-all hover:bg-slate-50 hover:border-primary/50 hover:shadow-sm ${source === "clara" ? "ring-2 ring-primary border-transparent" : "bg-white"
                  }`}
                onClick={() => setSource("clara")}
              >
                <div className="flex h-12 w-12 items-center justify-center rounded-full bg-purple-50">
                  <Sparkles className="h-6 w-6 text-purple-600" />
                </div>
                <div>
                  <p className="font-semibold text-foreground">Crear con Clara</p>
                  <p className="text-sm text-muted-foreground">
                    El asistente te ayuda a redactar el documento
                  </p>
                </div>
              </div>
            </div>

            <Button
              className="w-full"
              disabled={!source}
              onClick={() => {
                if (source === "clara") {
                  navigate("/clara");
                } else {
                  setStep("upload");
                }
              }}
            >
              Continuar
              <ArrowRight className="ml-2 h-4 w-4" />
            </Button>
          </div>
        );

      case "upload":
        return (
          <div className="space-y-4">
            <h2 className="text-lg font-semibold">Subir documento</h2>

            <div
              className="rounded-lg border-2 border-dashed border-muted-foreground/25 p-8 text-center transition-colors hover:bg-muted/50"
              onDragOver={(e) => e.preventDefault()}
              onDrop={handleDrop}
            >
              <div className="mx-auto mb-4 flex h-12 w-12 items-center justify-center rounded-full bg-muted">
                <FileText className="h-6 w-6 text-muted-foreground" />
              </div>
              <p className="mb-2 text-sm text-muted-foreground">
                Arrastra un PDF aquí o
              </p>
              <Label htmlFor="file-upload" className="cursor-pointer">
                <Button variant="secondary" size="sm" asChild>
                  <span>Seleccionar archivo</span>
                </Button>
              </Label>
              <Input
                id="file-upload"
                type="file"
                accept=".pdf"
                className="hidden"
                onChange={handleFileChange}
              />
              <p className="mt-2 text-xs text-muted-foreground">Máximo 10MB</p>
            </div>

            {file && (
              <div className="flex items-center gap-2 rounded-lg bg-muted p-3">
                <FileText className="h-5 w-5 text-muted-foreground" />
                <span className="flex-1 text-sm truncate">{file.name}</span>
                <Button variant="ghost" size="sm" onClick={() => setFile(null)} className="h-auto p-1">Change</Button>
              </div>
            )}

            <div className="space-y-2">
              <Label htmlFor="title">Título del documento</Label>
              <Input
                id="title"
                placeholder="Ej: Presupuesto diseño web"
                value={title}
                onChange={(e) => setTitle(e.target.value)}
              />
            </div>

            <Button className="w-full" disabled={!file || !title} onClick={() => setStep("signer")}>
              Continuar
              <ArrowRight className="ml-2 h-4 w-4" />
            </Button>
          </div>
        );

      case "signer":
        return (
          <div className="space-y-4">
            <h2 className="text-lg font-semibold">¿Quién debe firmar?</h2>

            <div className="space-y-4">
              <div className="space-y-4">
                <div className="grid gap-4 md:grid-cols-2">
                  <div className="space-y-2">
                    <Label htmlFor="name">Nombre / Razón Social *</Label>
                    <Input
                      id="name"
                      placeholder="Ej: Juan Pérez"
                      value={signerName}
                      onChange={(e) => setSignerName(e.target.value)}
                    />
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="nif">CIF / NIF *</Label>
                    <Input
                      id="nif"
                      placeholder="Ej: 12345678Z"
                      value={signerNif}
                      onChange={(e) => setSignerNif(e.target.value)}
                    />
                  </div>
                </div>

                <div className="space-y-2">
                  <Label htmlFor="email">Email *</Label>
                  <Input
                    id="email"
                    type="email"
                    placeholder="Ej: juan@email.com"
                    value={signerEmail}
                    onChange={(e) => setSignerEmail(e.target.value)}
                  />
                </div>

                <div className="grid gap-4 md:grid-cols-2">
                  <div className="space-y-2">
                    <Label htmlFor="phone">Teléfono *</Label>
                    <Input
                      id="phone"
                      placeholder="+34 600..."
                      value={signerPhone}
                      onChange={(e) => setSignerPhone(e.target.value)}
                    />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="address">Dirección *</Label>
                    <Input
                      id="address"
                      placeholder="Calle, Ciudad..."
                      value={signerAddress}
                      onChange={(e) => setSignerAddress(e.target.value)}
                    />
                  </div>
                </div>

              </div>

              <div className="space-y-3">
                <Label>Tipo de firma</Label>
                <RadioGroup value={signatureType} onValueChange={setSignatureType}>
                  <div className="space-y-2">
                    <label className="flex cursor-pointer items-start gap-3 rounded-lg border p-3 transition-colors hover:bg-accent [&:has(:checked)]:ring-2 [&:has(:checked)]:ring-primary">
                      <RadioGroupItem value="full" className="mt-0.5" />
                      <div className="flex-1">
                        <div className="flex items-center gap-2">
                          <p className="font-medium">Checkbox + nombre + firma</p>
                          <span className="rounded-full bg-primary/10 px-2 py-0.5 text-xs font-medium text-primary">
                            Recomendado
                          </span>
                        </div>
                        <p className="text-sm text-muted-foreground">Máxima prueba</p>
                      </div>
                    </label>

                    <label className="flex cursor-pointer items-start gap-3 rounded-lg border p-3 transition-colors hover:bg-accent [&:has(:checked)]:ring-2 [&:has(:checked)]:ring-primary">
                      <RadioGroupItem value="name" className="mt-0.5" />
                      <div>
                        <p className="font-medium">Checkbox + nombre</p>
                        <p className="text-sm text-muted-foreground">Confirmación con nombre</p>
                      </div>
                    </label>
                  </div>
                </RadioGroup>
              </div>

              <Button
                className="w-full"
                disabled={!signerName || !signerEmail || !signerNif || !signerPhone || !signerAddress}
                onClick={() => setStep("options")}
              >
                Continuar
                <ArrowRight className="ml-2 h-4 w-4" />
              </Button>
            </div>
          </div>
        );

      case "options":
        return (
          <div className="space-y-4">
            <h2 className="text-lg font-semibold">Opciones adicionales</h2>

            <div className="space-y-2">
              <Label htmlFor="message">Mensaje para el firmante (opcional)</Label>
              <Textarea
                id="message"
                placeholder="Ej: Hola Juan, te envío el presupuesto que comentamos."
                rows={3}
                value={customMessage}
                onChange={(e) => setCustomMessage(e.target.value)}
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="deadline">Plazo para firmar</Label>
              <Select value={expiresInDays} onValueChange={setExpiresInDays}>
                <SelectTrigger>
                  <SelectValue placeholder="Selecciona un plazo" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="3">3 días</SelectItem>
                  <SelectItem value="7">7 días</SelectItem>
                  <SelectItem value="15">15 días</SelectItem>
                  <SelectItem value="30">30 días</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <div className="rounded-lg bg-warning/10 p-3 text-sm text-warning">
              <p>
                ⚠️ Recuerda: FirmaClara genera prueba técnica de firma. Para contratos de alto riesgo, considera firma cualificada.
              </p>
            </div>

            <Button className="w-full" onClick={() => setStep("confirm")}>
              Revisar y enviar
              <ArrowRight className="ml-2 h-4 w-4" />
            </Button>
          </div>
        );

      case "confirm":
        return (
          <div className="space-y-4">
            <h2 className="text-lg font-semibold">Confirmar envío</h2>

            <Card>
              <CardContent className="p-4">
                <div className="flex items-start gap-3">
                  <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-lg bg-muted">
                    <FileText className="h-6 w-6 text-muted-foreground" />
                  </div>
                  <div>
                    <p className="font-medium truncate max-w-[200px]">{title}</p>
                    <p className="text-sm text-muted-foreground">PDF, {file ? (file.size / 1024).toFixed(0) : 0} KB</p>
                  </div>
                </div>
              </CardContent>
            </Card>

            <div className="space-y-2 text-sm">
              <div className="flex justify-between">
                <span className="text-muted-foreground">Firmante</span>
                <div className="text-right">
                  <p>{signerName}</p>
                  <p className="text-xs text-muted-foreground">{signerEmail}</p>
                  {signerNif && <p className="text-xs text-muted-foreground">NIF: {signerNif}</p>}
                  {signerPhone && <p className="text-xs text-muted-foreground">{signerPhone}</p>}
                </div>
              </div>
              <div className="flex justify-between">
                <span className="text-muted-foreground">Tipo de firma</span>
                <span>
                  {signatureType === 'full' ? 'Checkbox + nombre + firma' :
                    signatureType === 'name' ? 'Checkbox + nombre' : 'Básica'}
                </span>
              </div>
              <div className="flex justify-between">
                <span className="text-muted-foreground">Plazo</span>
                <span>{expiresInDays} días</span>
              </div>
            </div>

            <div className="rounded-lg bg-primary/5 p-3 text-center">
              <p className="text-sm">
                💳 Se usará <strong>1 crédito</strong>
              </p>
              <p className="text-xs text-muted-foreground text-opacity-50">(Se descontará al enviar)</p>
            </div>

            <Button
              className="w-full"
              size="lg"
              onClick={handleCreateDocument}
              disabled={isSubmitting}
            >
              {isSubmitting ? (
                <>
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  Enviando...
                </>
              ) : (
                'Enviar documento'
              )}
            </Button>
          </div>
        );
    }
  };

  return (
    <div className="mx-auto max-w-xl py-4 space-y-6">
      <div className="flex items-center gap-3 px-1">
        <Button
          variant="ghost"
          size="icon"
          className="h-8 w-8"
          onClick={() => {
            if (step === "source") {
              navigate("/dashboard");
            } else if (step === "upload") {
              setStep("source");
            } else if (step === "signer") {
              setStep("upload");
            } else if (step === "options") {
              setStep("signer");
            } else if (step === "confirm") {
              setStep("options");
            }
          }}
          disabled={isSubmitting}
        >
          <ArrowLeft className="h-4 w-4" />
        </Button>
        <h1 className="text-xl font-bold tracking-tight">Nuevo documento</h1>
      </div>

      <div className="mx-1 flex gap-2">
        {["source", "upload", "signer", "options", "confirm"].map((s, i) => (
          <div
            key={s}
            className={`h-1.5 flex-1 rounded-full transition-colors ${["source", "upload", "signer", "options", "confirm"].indexOf(step) >= i
              ? "bg-primary"
              : "bg-slate-200"
              }`}
          />
        ))}
      </div>

      <Card className="border-muted/40 shadow-lg">
        <CardContent className="p-6">{renderStep()}</CardContent>
      </Card>
    </div>
  );
}
