// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pmzfwwtgjvlvuawxguiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtemZ3d3RnanZsdnVhd3hndWl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg5MTY5MTYsImV4cCI6MjA4NDQ5MjkxNn0.I8g7sgIuzhsuT-lrluuDq0bWs4eSim0ImFiKZokem-I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});